version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    command: pnpm run start
    env_file:
      - .env
    # Protect node_modules from being overwritten
#    volumes:
#      - .:/app
#      - /app/node_modules

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: fastifydb
      POSTGRES_USER: fastifyuser
      POSTGRES_PASSWORD: fastifypass
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
